version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8080:80"
    networks:
      - web
    volumes:
      - "/home/benton/nextcloud:/var/www/html"
      - "${STORAGE_VOLUME}:/var/www/html/data"
    environment:
      VIRTUAL_HOST: "c.${DOMAIN}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "c.${DOMAIN}"
      LETSENCRYPT_EMAIL: benton.anderson@gmail.com
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${NEXTCLOUD_POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${NEXTCLOUD_POSTGRES_HOST}

  jupyter:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    networks:
      - web
    command: >
      start-notebook.sh
      --NotebookApp.password='${JUPYTER_PASSWORD_HASHED}'
    volumes:
      - "/home/benton/notebooks:/home/jovyan/work"
    environment:
      VIRTUAL_HOST: "j.${DOMAIN}"
      VIRTUAL_PORT: 8888
      LETSENCRYPT_HOST: "j.${DOMAIN}"
      LETSENCRYPT_EMAIL: benton.anderson@gmail.com

configs:
  proxy_config:
    file: ./proxy.conf

networks:
  web:

