version: "3.3"

services:  
  jupyter:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    command: >
      start-notebook.sh 
      --NotebookApp.password='${JUPYTER_PASSWORD_HASHED}'
      --NotebookApp.base_url='/j'
    volumes:
      - "/home/benton/notebooks:/home/jovyan/work"

